### ISSUE TITLE
polygon in counter clockwise the split doesnt work properly

### ISSUE THREAD

**Issue by thealves** [rowanwins/polygon-splitter#8]
still have the issue, just upgraded to 0.0.6 but creating a polygon in counter clockwise, the split doesnt work properly

![image](https://user-images.githubusercontent.com/55852987/148826796-98f69a08-edee-4eed-ae69-f9b49ba85bb8.png)

_Originally posted by @thealves in https://github.com/rowanwins/polygon-splitter/issues/7#issuecomment-1009270011_

**Comment by rowanwins** [comment]
@thealves could you please share your geojson inputs, I'm struggling to replicate

**Comment by thealves** [comment]
Polygon: 
{"type":"Polygon","coordinates":[[[56.038294599616435,-91.89644024062605],[56.01987804345656,-91.17655228740313],[56.26928626839682,-91.15457097585437],[56.27691126048011,-91.81401032231811],[56.038294599616435,-91.89644024062605]]]}

Lines: (in this case im using MultiLineString, but with LineString it has the same issue)
{"type":"MultiLineString","coordinates":[[[56.386542701886306,-91.57705734043186],[56.18989620919031,-91.50564436022233],[55.963038336795684,-91.85996260818509]]]}


Polygon splitter return:
{"type":"Feature","properties":{},"geometry":{"type":"MultiPolygon","coordinates":[[[[56.27369756367859,-91.53607716574841],[56.27691126048011,-91.81401032231811],[56.038294599616435,-91.89644024062605],[56.03450584591102,-91.7483409908759],[55.963038336795684,-91.85996260818509],[56.01987804345656,-91.17655228740313],[56.26928626839682,-91.15457097585437],[56.27369756367859,-91.53607716574841]]],[[[56.03450584591102,-91.7483409908759],[56.01987804345656,-91.17655228740313],[56.26928626839682,-91.15457097585437],[56.27369756367859,-91.53607716574841],[56.386542701886306,-91.57705734043186],[56.27691126048011,-91.81401032231811],[56.038294599616435,-91.89644024062605],[56.03450584591102,-91.7483409908759]]]]}}

**Comment by rowanwins** [comment]
I've just published v0.0.7 which now includes an extra step at the beginning to ensure the input polygon winding order is correct.
